
StufDB = {
	["boss1"] = {
		["text2"] = {
			["pattern"] = "[curhp]",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 85,
			["framelevel"] = 2,
			["y"] = -5,
			["x"] = 0,
			["fontsize"] = 12,
			["justifyH"] = "RIGHT",
			["fontflags"] = "OUTLINE",
			["h"] = 20,
			["justifyV"] = "TOP",
			["hide"] = true,
		},
		["portrait"] = {
			["bgcolor"] = {
				["a"] = 0,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 1,
				["g"] = 0.855,
				["b"] = 0,
			},
			["w"] = 60,
			["y"] = 18,
			["x"] = -64,
			["h"] = 60,
			["camera"] = 1,
			["alpha"] = 1,
			["border"] = "None",
			["bg"] = "Steel",
			["hide"] = true,
		},
		["castbar"] = {
			["spellfontsize"] = 14,
			["bgcolor"] = {
				["a"] = 0.367,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["timeshadowy"] = -1,
			["spelljustifyH"] = "RIGHT",
			["iconw"] = 1,
			["h"] = 6,
			["timefontsize"] = 16,
			["timefontflags"] = "OUTLINE",
			["timeh"] = 20,
			["spellfontcolor"] = {
				["a"] = 1,
				["b"] = 0.969,
				["g"] = 1,
				["r"] = 0.992,
			},
			["w"] = 175,
			["spelljustifyV"] = "BOTTOM",
			["y"] = 15,
			["x"] = 0,
			["iconalpha"] = 1,
			["timejustifyV"] = "TOP",
			["timefontcolor"] = {
				["a"] = 1,
				["b"] = 0.953,
				["g"] = 0.969,
				["r"] = 0.953,
			},
			["baralpha"] = 1,
			["spellh"] = 16,
			["timefont"] = "傷害數字",
			["border"] = "Blizzard Tooltip",
			["iconh"] = 1,
			["lagcolor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0.035,
				["r"] = 1,
			},
			["timew"] = 120,
			["spelly"] = 20,
			["timeformat"] = "none",
			["bordercolor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0.82,
				["r"] = 1,
			},
			["timey"] = -10,
			["spellx"] = 0,
			["bartexture"] = "Blizzard",
			["timeshadowx"] = 1,
			["framelevel"] = 8,
			["alpha"] = 1,
			["spellfontflags"] = "OUTLINE",
			["spellshadowy"] = -1,
			["icony"] = 16,
			["spellw"] = 140,
			["spellshadowx"] = 1,
			["timejustifyH"] = "RIGHT",
			["showlag"] = true,
			["timex"] = 0,
			["iconx"] = -48,
		},
		["text3"] = {
			["pattern"] = "[perchp]%",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 80,
			["framelevel"] = 2,
			["y"] = -5,
			["font"] = "傷害數字",
			["fontsize"] = 14,
			["h"] = 20,
			["fontflags"] = "OUTLINE",
			["justifyV"] = "TOP",
			["justifyH"] = "CENTER",
			["x"] = 0,
		},
		["infoicon"] = {
			["y"] = 20,
			["x"] = -38,
			["circular"] = true,
			["hide"] = true,
			["h"] = 30,
			["w"] = 30,
			["framelevel"] = 2,
		},
		["debuffgroup"] = {
			["h"] = 30,
			["w"] = 30,
			["push"] = "None",
			["showpie"] = true,
			["rows"] = 1,
			["growth"] = "LRBT",
			["cols"] = 10,
			["y"] = -28,
			["pieonlymine"] = true,
			["count"] = 5,
			["spacing"] = 2,
			["counttfontflags"] = "OUTLINE",
			["vspacing"] = 1,
			["x"] = 180,
			["onlymine"] = true,
		},
		["hpbar"] = {
			["baralpha"] = 1,
			["bgcolor"] = {
				["a"] = 0,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bartexture"] = "Blizzard",
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 1,
				["g"] = 0.796,
				["b"] = 0,
			},
			["bgalpha"] = 0.3,
			["w"] = 80,
			["bgcolormethod"] = "classdark",
			["y"] = 1,
			["x"] = 0,
			["border"] = "None",
			["barcolormethod"] = "class",
			["fade"] = true,
			["h"] = 10,
			["inc"] = true,
			["framelevel"] = 1,
		},
		["mpbar"] = {
			["baralpha"] = 1,
			["bartexture"] = "Blizzard",
			["bgalpha"] = 0.3,
			["border"] = "Blizzard Tooltip",
			["framelevel"] = 1,
			["y"] = 0,
			["x"] = 95,
			["h"] = 8,
			["barcolormethod"] = "power",
			["w"] = 80,
			["fade"] = true,
			["bgcolormethod"] = "powerdark",
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 0,
				["g"] = 0.749,
				["b"] = 1,
			},
		},
		["text4"] = {
			["pattern"] = "[curmp]",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 80,
			["framelevel"] = 2,
			["y"] = -5,
			["x"] = 95,
			["fontsize"] = 12,
			["h"] = 20,
			["fontflags"] = "OUTLINE",
			["justifyV"] = "TOP",
			["justifyH"] = "RIGHT",
			["font"] = "預設",
		},
		["buffgroup"] = {
			["timey"] = 0,
			["rows"] = 1,
			["w"] = 20,
			["cols"] = 10,
			["y"] = 25,
			["x"] = 268,
			["count"] = 5,
			["spacing"] = 2,
			["vspacing"] = 5,
			["h"] = 20,
			["onlymine"] = true,
		},
		["raidtargeticon"] = {
			["y"] = 20,
			["h"] = 26,
			["x"] = -35,
			["w"] = 26,
			["framelevel"] = 6,
		},
		["frame"] = {
			["y"] = -334,
			["x"] = 1167,
			["bordercolormethod"] = "classreaction",
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 1,
				["g"] = 0.906,
				["b"] = 0,
			},
			["w"] = 80,
			["h"] = 6,
		},
		["text1"] = {
			["pattern"] = "[class:name]",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["justifyV"] = "TOP",
			["framelevel"] = 2,
			["y"] = 24,
			["x"] = -72,
			["fontsize"] = 16,
			["w"] = 200,
			["fontflags"] = "OUTLINE",
			["font"] = "預設",
			["h"] = 16,
			["justifyH"] = "LEFT",
		},
		["threatbar"] = {
			["y"] = -10,
			["h"] = 14,
			["bgcolor"] = {
				["a"] = 0.4,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["x"] = 0,
			["fontsize"] = 12,
			["w"] = 40,
			["framelevel"] = 4,
		},
	},
	["arenapet4"] = {
		["frame"] = {
			["y"] = -480,
			["h"] = 24,
			["x"] = 1127,
			["w"] = 78,
			["hide"] = true,
		},
	},
	["party3"] = {
		["frame"] = {
			["y"] = -469,
			["x"] = 41,
		},
	},
	["party1target"] = {
		["frame"] = {
			["y"] = -234,
			["x"] = 212,
		},
	},
	["boss4target"] = {
		["frame"] = {
			["y"] = -496,
			["x"] = 1349,
			["w"] = 78,
			["h"] = 24,
		},
	},
	["target"] = {
		["buffgroup"] = {
			["h"] = 20,
			["timeonlymine"] = true,
			["x"] = 0,
			["rows"] = 2,
			["growth"] = "LRTB",
			["cols"] = 10,
			["y"] = -39,
			["pieonlymine"] = true,
			["count"] = 10,
			["spacing"] = 2,
			["timefontsize"] = 1,
			["vspacing"] = 5,
			["counttx"] = 0,
			["w"] = 20,
		},
		["portrait"] = {
			["zoom2d"] = true,
			["bgcolor"] = {
				["a"] = 0,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["bordercolor"] = {
				["a"] = 0.777,
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["w"] = 60,
			["y"] = 18,
			["h"] = 60,
			["x"] = -64,
			["alpha"] = 1,
			["border"] = "None",
			["bg"] = "Steel",
			["camera"] = 1,
		},
		["combattext"] = {
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 250,
			["framelevel"] = 4,
			["y"] = -2,
			["x"] = 0,
			["fontsize"] = 12,
			["justifyV"] = "TOP",
			["h"] = 14,
			["justifyH"] = "RIGHT",
			["hide"] = true,
		},
		["text3"] = {
			["pattern"] = "[curhp] - [perchp]%",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 245,
			["framelevel"] = 2,
			["y"] = -3,
			["x"] = 3,
			["fontsize"] = 12,
			["fontflags"] = "None",
			["h"] = 12,
			["justifyH"] = "LEFT",
			["justifyV"] = "BOTTOM",
		},
		["infoicon"] = {
			["y"] = -25,
			["x"] = -25,
			["circular"] = true,
			["hide"] = true,
			["h"] = 24,
			["w"] = 24,
			["framelevel"] = 2,
		},
		["debuffgroup"] = {
			["rows"] = 2,
			["counttshadowx"] = 0,
			["cols"] = 8,
			["h"] = 40,
			["spacing"] = 2,
			["vspacing"] = 1,
			["counttfontflags"] = "OUTLINE",
			["timeshadowx"] = 0,
			["curable"] = true,
			["w"] = 40,
			["x"] = 0,
			["y"] = -64,
			["push"] = "None",
			["count"] = 16,
			["showpie"] = true,
			["pieonlymine"] = true,
			["growth"] = "LRTB",
			["counttfontsize"] = 1,
			["onlymine"] = true,
		},
		["text7"] = {
			["pattern"] = "",
			["shadowy"] = -1,
			["w"] = 1,
			["framelevel"] = 2,
			["y"] = 0,
			["x"] = 0,
			["fontsize"] = 10,
			["justifyV"] = "CENTER",
			["h"] = 1,
			["justifyH"] = "CENTER",
			["hide"] = true,
		},
		["threatbar"] = {
			["y"] = -25,
			["x"] = 210,
			["fontsize"] = 12,
			["h"] = 14,
			["bgcolor"] = {
				["a"] = 0.4,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["w"] = 40,
			["framelevel"] = 4,
		},
		["text6"] = {
			["pattern"] = "[gray_if_oor:距離過遠][gray_if_offline:離線][gray_if_dead:死亡][gray_if_ghost:靈魂]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 246,
			["framelevel"] = 4,
			["y"] = 2,
			["x"] = 0,
			["fontsize"] = 16,
			["justifyH"] = "CENTER",
			["justifyV"] = "CENTER",
			["font"] = "傷害數字",
			["h"] = 20,
		},
		["hpbar"] = {
			["baralpha"] = 1,
			["bartexture"] = "Flat Smooth",
			["bgcolormethod"] = "classreactiondark",
			["bordercolor"] = {
				["a"] = 0.645,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["border"] = "Square Outline",
			["framelevel"] = 1,
			["y"] = 0,
			["x"] = 0,
			["w"] = 250,
			["barcolormethod"] = "classreaction",
			["h"] = 16,
			["fade"] = true,
			["inc"] = true,
			["bgalpha"] = 0.3,
		},
		["text1"] = {
			["pattern"] = "[classreaction:name]",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 250,
			["framelevel"] = 2,
			["y"] = 18,
			["x"] = 0,
			["fontsize"] = 16,
			["h"] = 16,
			["fontflags"] = "None",
			["font"] = "預設",
			["justifyH"] = "LEFT",
			["justifyV"] = "TOP",
		},
		["text2"] = {
			["pattern"] = "[class_if_npc:creaturetype][class_if_pc:race] [difficulty:level][difficulty:classification]",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 250,
			["framelevel"] = 2,
			["y"] = 15,
			["x"] = 0,
			["fontsize"] = 12,
			["justifyV"] = "TOP",
			["h"] = 12,
			["justifyH"] = "RIGHT",
		},
		["comboframe"] = {
			["glowcolor"] = {
				["a"] = 0.8,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["framelevel"] = 10,
			["combo3color"] = {
				["a"] = 1,
				["b"] = 0.149,
				["g"] = 0.867,
				["r"] = 1,
			},
			["combo5color"] = {
				["a"] = 1,
				["b"] = 0.051,
				["g"] = 0.141,
				["r"] = 1,
			},
			["color"] = {
				["a"] = 1,
				["r"] = 0.7,
				["g"] = 0,
				["b"] = 0,
			},
			["combo4color"] = {
				["a"] = 1,
				["b"] = 0.125,
				["g"] = 0.529,
				["r"] = 1,
			},
			["combo1color"] = {
				["a"] = 1,
				["b"] = 0.145,
				["g"] = 1,
				["r"] = 0.984,
			},
			["combo1h"] = 10,
			["y"] = -27,
			["x"] = 90,
			["combo2color"] = {
				["a"] = 1,
				["b"] = 0.118,
				["g"] = 1,
				["r"] = 0.969,
			},
			["combo6color"] = {
				["a"] = 1,
				["b"] = 0.035,
				["g"] = 0.125,
				["r"] = 1,
			},
			["h"] = 20,
			["combo1w"] = 10,
			["combostyle"] = 2,
			["w"] = 150,
		},
		["grouptext"] = {
			["bgcolor"] = {
				["a"] = 0.3,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 16,
			["framelevel"] = 3,
			["y"] = 18,
			["x"] = -18,
			["fontsize"] = 16,
			["h"] = 16,
			["justifyH"] = "CENTER",
			["justifyV"] = "CENTER",
			["font"] = "傷害數字",
		},
		["mpbar"] = {
			["baralpha"] = 1,
			["bartexture"] = "Flat Smooth",
			["bgalpha"] = 0,
			["border"] = "Square Outline",
			["framelevel"] = 1,
			["y"] = -16,
			["x"] = 0,
			["h"] = 7,
			["barcolormethod"] = "power",
			["bgcolormethod"] = "power",
			["fade"] = true,
			["bordercolor"] = {
				["a"] = 0.512,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["w"] = 250,
		},
		["lfgicon"] = {
			["y"] = 20,
			["x"] = -70,
			["circular"] = true,
			["h"] = 24,
			["w"] = 24,
			["alpha"] = 1,
			["framelevel"] = 4,
		},
		["text8"] = {
			["pattern"] = "",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 1,
			["framelevel"] = 2,
			["y"] = 0,
			["x"] = 0,
			["fontsize"] = 16,
			["font"] = "預設",
			["justifyH"] = "RIGHT",
			["justifyV"] = "CENTER",
			["h"] = 1,
		},
		["castbar"] = {
			["spellfontsize"] = 16,
			["bgcolor"] = {
				["a"] = 1,
				["b"] = 0.173,
				["g"] = 0.18,
				["r"] = 0.18,
			},
			["timeshadowy"] = -1,
			["spelljustifyH"] = "LEFT",
			["iconw"] = 36,
			["h"] = 18,
			["timefontsize"] = 12,
			["timeh"] = 12,
			["spellfontcolor"] = {
				["a"] = 1,
				["b"] = 0.969,
				["g"] = 1,
				["r"] = 0.992,
			},
			["w"] = 218,
			["spelljustifyV"] = "CENTER",
			["y"] = -40,
			["x"] = 32,
			["iconx"] = -34,
			["timejustifyV"] = "CENTER",
			["spellw"] = 250,
			["baralpha"] = 1,
			["spellh"] = 16,
			["border"] = "None",
			["iconh"] = 32,
			["lagcolor"] = {
				["a"] = 0.6,
				["b"] = 0,
				["g"] = 0,
				["r"] = 1,
			},
			["bordercolor"] = {
				["a"] = 0.76,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["spellshadowy"] = -1,
			["spelly"] = 16,
			["timeformat"] = "remaindurationdelay",
			["bartexture"] = "Glaze2",
			["spellx"] = 5,
			["timey"] = -4,
			["timeshadowx"] = 1,
			["timew"] = 250,
			["alpha"] = 1,
			["spellfontflags"] = "OUTLINE",
			["timefontcolor"] = {
				["a"] = 1,
				["b"] = 0.953,
				["g"] = 0.969,
				["r"] = 0.953,
			},
			["icony"] = 14,
			["framelevel"] = 9,
			["spellshadowx"] = 1,
			["timejustifyH"] = "LEFT",
			["showlag"] = true,
			["timex"] = 10,
			["iconalpha"] = 1,
		},
		["text5"] = {
			["pattern"] = "[percmp]%",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 250,
			["framelevel"] = 2,
			["y"] = -24,
			["x"] = 0,
			["fontsize"] = 12,
			["justifyV"] = "BOTTOM",
			["h"] = 12,
			["justifyH"] = "RIGHT",
			["hide"] = true,
		},
		["leadericon"] = {
			["y"] = 38,
			["x"] = 0,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["pvpicon"] = {
			["y"] = -3,
			["x"] = -76,
			["h"] = 24,
			["w"] = 24,
			["framelevel"] = 4,
		},
		["dispellicon"] = {
			["y"] = 20,
			["x"] = 110,
			["h"] = 36,
			["w"] = 36,
			["framelevel"] = 4,
		},
		["looticon"] = {
			["y"] = 38,
			["x"] = 18,
			["h"] = 18,
			["w"] = 18,
			["framelevel"] = 4,
		},
		["rangetext"] = {
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 100,
			["framelevel"] = 4,
			["y"] = -27,
			["h"] = 10,
			["justifyH"] = "LEFT",
			["fontsize"] = 12,
			["x"] = 216,
		},
		["auratimers"] = {
			["rows"] = 6,
			["w"] = 70,
			["cols"] = 2,
			["y"] = -42,
			["x"] = 265,
			["count"] = 12,
			["push"] = "None",
			["h"] = 15,
			["growth"] = "TBLR",
			["hide"] = true,
		},
		["text4"] = {
			["pattern"] = "[curmp]/[maxmp]",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 141,
			["framelevel"] = 2,
			["y"] = -20,
			["x"] = 0,
			["fontsize"] = 12,
			["justifyH"] = "RIGHT",
			["justifyV"] = "BOTTOM",
			["h"] = 12,
		},
		["raidtargeticon"] = {
			["y"] = 45,
			["x"] = -28,
			["h"] = 26,
			["w"] = 26,
			["framelevel"] = 4,
		},
		["frame"] = {
			["y"] = -50,
			["x"] = 500,
			["bordercolormethod"] = "solid",
			["bordercolor"] = {
				["a"] = 0,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["w"] = 250,
			["h"] = 27,
		},
		["inspectbutton"] = {
			["y"] = 40,
			["x"] = -25,
			["framelevel"] = 6,
			["h"] = 24,
			["w"] = 24,
			["hide"] = true,
		},
		["statusicon"] = {
			["y"] = -26,
			["x"] = -72,
			["h"] = 24,
			["w"] = 24,
			["framelevel"] = 4,
		},
	},
	["arenapet2"] = {
		["frame"] = {
			["y"] = -386,
			["h"] = 24,
			["x"] = 1127,
			["w"] = 78,
			["hide"] = true,
		},
	},
	["boss2"] = {
		["frame"] = {
			["y"] = -392,
			["h"] = 24,
			["w"] = 78,
			["x"] = 1167,
		},
	},
	["arena1"] = {
		["text2"] = {
			["y"] = 0,
			["x"] = 0,
			["pattern"] = "",
			["h"] = 10,
			["w"] = 54,
			["hide"] = true,
		},
		["portrait"] = {
			["y"] = 0,
			["x"] = 0,
			["w"] = 24,
			["h"] = 24,
		},
		["castbar"] = {
			["baralpha"] = 0,
			["spellfontsize"] = 10,
			["bgcolor"] = {
				["a"] = 0.2,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["spellh"] = 12,
			["spelljustifyH"] = "CENTER",
			["iconh"] = 14,
			["iconw"] = 14,
			["h"] = 26,
			["spellshadowy"] = -1,
			["y"] = 1,
			["spellw"] = 80,
			["timefontsize"] = 8,
			["timejustifyH"] = "CENTER",
			["spellshadowx"] = -1,
			["w"] = 80,
			["timew"] = 80,
			["spellx"] = 0,
			["timey"] = 0,
			["timeh"] = 26,
			["spellfontcolor"] = {
				["a"] = 0.7,
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.2,
			},
			["alpha"] = 1,
			["spelljustifyV"] = "CENTER",
			["spelly"] = -12,
			["x"] = -1,
			["icony"] = 0,
			["iconx"] = -16,
			["timejustifyV"] = "CENTER",
			["timefontcolor"] = {
				["a"] = 0,
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.2,
			},
			["timex"] = 0,
			["iconalpha"] = 0,
		},
		["text3"] = {
			["y"] = -13,
			["x"] = 25,
			["pattern"] = "[perchp]%",
			["h"] = 10,
			["w"] = 54,
			["fontsize"] = 10,
			["justifyV"] = "CENTER",
			["justifyH"] = "CENTER",
		},
		["infoicon"] = {
			["y"] = 0,
			["x"] = 0,
			["h"] = 12,
			["w"] = 12,
			["hide"] = true,
		},
		["debuffgroup"] = {
			["rows"] = 1,
			["w"] = 10,
			["cols"] = 8,
			["y"] = -23,
			["x"] = 0,
			["count"] = 8,
			["h"] = 10,
			["growth"] = "LRTB",
			["push"] = "v",
		},
		["mpbar"] = {
			["y"] = -19,
			["x"] = 24,
			["barcolormethod"] = "power",
			["h"] = 5,
			["bgalpha"] = 0.3,
			["w"] = 53,
			["bgcolormethod"] = "powerdark",
		},
		["hpbar"] = {
			["y"] = -1,
			["x"] = 24,
			["barcolormethod"] = "hpgreen",
			["h"] = 17,
			["bgalpha"] = 0.3,
			["w"] = 53,
			["bgcolormethod"] = "hpgreendark",
		},
		["text4"] = {
			["y"] = 0,
			["x"] = 0,
			["pattern"] = "",
			["h"] = 10,
			["w"] = 54,
			["hide"] = true,
		},
		["frame"] = {
			["y"] = -327,
			["h"] = 24,
			["x"] = 1164,
			["w"] = 78,
			["hide"] = true,
		},
		["text1"] = {
			["pattern"] = "[class:name]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 54,
			["y"] = 0,
			["x"] = 25,
			["fontsize"] = 12,
			["h"] = 12,
			["justifyH"] = "LEFT",
			["justifyV"] = "TOP",
		},
		["buffgroup"] = {
			["y"] = -24,
			["x"] = 0,
			["count"] = 8,
			["h"] = 10,
			["w"] = 10,
			["rows"] = 1,
			["growth"] = "LRTB",
			["cols"] = 8,
		},
	},
	["boss5target"] = {
		["frame"] = {
			["y"] = -560,
			["x"] = 1349,
			["w"] = 78,
			["h"] = 24,
		},
	},
	["arenapet1"] = {
		["text2"] = {
			["y"] = 0,
			["x"] = 0,
			["pattern"] = "[perchp]",
			["h"] = 12,
			["w"] = 24,
			["fontsize"] = 9,
			["justifyV"] = "CENTER",
			["justifyH"] = "CENTER",
		},
		["portrait"] = {
			["y"] = 0,
			["x"] = 24,
			["w"] = 12,
			["h"] = 12,
		},
		["text3"] = {
			["y"] = 0,
			["x"] = 0,
			["pattern"] = "",
			["fontsize"] = 10,
			["h"] = 10,
			["w"] = 10,
			["hide"] = true,
		},
		["infoicon"] = {
			["y"] = 0,
			["x"] = 0,
			["h"] = 12,
			["w"] = 12,
			["hide"] = true,
		},
		["debuffgroup"] = {
			["rows"] = 1,
			["w"] = 6,
			["cols"] = 6,
			["y"] = -12,
			["x"] = 0,
			["count"] = 6,
			["push"] = "v",
			["h"] = 6,
			["hide"] = true,
		},
		["mpbar"] = {
			["y"] = -9,
			["x"] = 0,
			["hide"] = true,
			["barcolormethod"] = "power",
			["h"] = 3,
			["bgalpha"] = 0.3,
			["w"] = 24,
			["bgcolormethod"] = "powerdark",
		},
		["hpbar"] = {
			["y"] = 0,
			["x"] = 0,
			["h"] = 12,
			["barcolormethod"] = "hpgreen",
			["reverse"] = true,
			["bgalpha"] = 0.3,
			["w"] = 24,
			["bgcolormethod"] = "hpgreendark",
		},
		["text4"] = {
			["y"] = 0,
			["x"] = 0,
			["pattern"] = "",
			["fontsize"] = 10,
			["h"] = 10,
			["w"] = 10,
			["hide"] = true,
		},
		["frame"] = {
			["y"] = -339,
			["h"] = 12,
			["x"] = 1127,
			["w"] = 36,
			["hide"] = true,
		},
		["text1"] = {
			["y"] = 0,
			["x"] = 0,
			["pattern"] = "",
			["h"] = 12,
			["w"] = 24,
			["hide"] = true,
		},
		["buffgroup"] = {
			["y"] = -12,
			["x"] = 0,
			["count"] = 6,
			["hide"] = true,
			["h"] = 6,
			["rows"] = 1,
			["w"] = 6,
			["cols"] = 6,
		},
	},
	["pet"] = {
		["buffgroup"] = {
			["rows"] = 2,
			["w"] = 17,
			["cols"] = 16,
			["y"] = -52,
			["h"] = 17,
			["count"] = 32,
			["growth"] = "LRTB",
			["x"] = 0,
			["hide"] = true,
		},
		["portrait"] = {
			["y"] = -1,
			["h"] = 48,
			["bgcolor"] = {
				["a"] = 0.4,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["show3d"] = true,
			["x"] = 1,
			["bg"] = "Flat Smooth",
			["w"] = 48,
			["hide"] = true,
		},
		["combattext"] = {
			["y"] = 1,
			["h"] = 12,
			["justifyH"] = "CENTER",
			["x"] = -1,
			["w"] = 40,
			["fontsize"] = 10,
			["justifyV"] = "TOP",
			["hide"] = true,
		},
		["text3"] = {
			["pattern"] = "[perchp]%",
			["w"] = 140,
			["y"] = -8,
			["h"] = 21,
			["fontsize"] = 14,
			["emptyhide"] = true,
			["justifyH"] = "LEFT",
			["x"] = 72,
			["justifyV"] = "TOP",
		},
		["infoicon"] = {
			["y"] = -37,
			["x"] = 50,
			["h"] = 12,
			["w"] = 12,
			["hide"] = true,
		},
		["debuffgroup"] = {
			["rows"] = 3,
			["w"] = 17,
			["cols"] = 16,
			["y"] = -52,
			["push"] = "v",
			["count"] = 40,
			["growth"] = "TBLR",
			["x"] = 0,
			["h"] = 17,
			["hide"] = true,
		},
		["text6"] = {
			["y"] = -21,
			["x"] = 1,
			["pattern"] = "[gray_if_dead:DEAD]",
			["justifyH"] = "CENTER",
			["justifyV"] = "CENTER",
			["h"] = 10,
			["w"] = 145,
			["fontsize"] = 10,
		},
		["text1"] = {
			["pattern"] = "[name]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 140,
			["y"] = 10,
			["x"] = 3,
			["fontsize"] = 14,
			["fontflags"] = "OUTLINE",
			["justifyV"] = "TOP",
			["justifyH"] = "LEFT",
			["h"] = 14,
		},
		["text2"] = {
			["onmouse"] = true,
			["pattern"] = "[level]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 140,
			["y"] = 8,
			["x"] = -140,
			["fontsize"] = 12,
			["h"] = 12,
			["justifyV"] = "TOP",
			["justifyH"] = "RIGHT",
		},
		["castbar"] = {
			["baralpha"] = 0,
			["spellfontsize"] = 12,
			["spellshadowy"] = -1,
			["spellh"] = 12,
			["spelljustifyH"] = "CENTER",
			["alpha"] = 1,
			["iconh"] = 12,
			["iconw"] = 12,
			["h"] = 40,
			["icony"] = -26,
			["timefontcolor"] = {
				["a"] = 0,
				["b"] = 0.2,
				["g"] = 0.5,
				["r"] = 1,
			},
			["iconhide"] = true,
			["timefontsize"] = 10,
			["timejustifyV"] = "CENTER",
			["hide"] = true,
			["iconx"] = 62,
			["timew"] = 147,
			["spellx"] = 0,
			["timey"] = -30,
			["timeh"] = 10,
			["spellfontcolor"] = {
				["a"] = 0.7,
				["b"] = 0.2,
				["g"] = 0.5,
				["r"] = 1,
			},
			["w"] = 147,
			["spelljustifyV"] = "CENTER",
			["y"] = 1,
			["x"] = -1,
			["spelly"] = -18,
			["spellshadowx"] = -1,
			["timejustifyH"] = "CENTER",
			["spellw"] = 147,
			["timex"] = 0,
			["bgcolor"] = {
				["a"] = 0.2,
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
		},
		["text5"] = {
			["y"] = -24,
			["x"] = -130,
			["pattern"] = "[percmp]%",
			["fontsize"] = 10,
			["w"] = 140,
			["justifyH"] = "RIGHT",
			["justifyV"] = "BOTTOM",
			["h"] = 10,
		},
		["dispellicon"] = {
			["y"] = -4,
			["x"] = 149,
			["h"] = 42,
			["w"] = 42,
			["hide"] = true,
		},
		["happinessicon"] = {
			["y"] = -2,
			["x"] = -15,
			["h"] = 16,
			["w"] = 16,
			["framelevel"] = 5,
		},
		["mpbar"] = {
			["baralpha"] = 1,
			["bgcolor"] = {
				["a"] = 1,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 0.012,
				["g"] = 0.012,
				["b"] = 0.012,
			},
			["w"] = 110,
			["fade"] = true,
			["y"] = -12,
			["h"] = 15,
			["framelevel"] = 0,
			["barcolormethod"] = "power",
			["x"] = -5,
			["bgcolormethod"] = "powerdark",
			["border"] = "Square Outline",
			["bgalpha"] = 1,
		},
		["pettime"] = {
			["y"] = -25,
			["h"] = 10,
			["fontsize"] = 10,
			["x"] = 0,
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 36,
			["hide"] = true,
		},
		["hpbar"] = {
			["bgcolor"] = {
				["a"] = 1,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bgalpha"] = 1,
			["w"] = 100,
			["fade"] = true,
			["y"] = 0,
			["x"] = 0,
			["barcolor"] = {
				["a"] = 1,
				["r"] = 0.302,
				["g"] = 0.302,
				["b"] = 0.302,
			},
			["barcolormethod"] = "class",
			["h"] = 20,
			["bgcolormethod"] = "classdark",
			["border"] = "Square Outline",
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
		},
		["raidtargeticon"] = {
			["y"] = -15,
			["h"] = 16,
			["x"] = 195,
			["w"] = 16,
			["hide"] = true,
		},
		["frame"] = {
			["y"] = -118,
			["h"] = 20,
			["bordercolor"] = {
				["a"] = 0,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["w"] = 100,
			["x"] = 33,
		},
		["text4"] = {
			["onmouse"] = true,
			["pattern"] = "[curhp]",
			["w"] = 126,
			["y"] = -8,
			["h"] = 10,
			["fontsize"] = 10,
			["emptyhide"] = true,
			["justifyH"] = "RIGHT",
			["x"] = -80,
			["justifyV"] = "BOTTOM",
		},
		["statusicon"] = {
			["y"] = 5,
			["x"] = -10,
			["h"] = 14,
			["w"] = 14,
			["hide"] = true,
		},
	},
	["boss4"] = {
		["frame"] = {
			["y"] = -511,
			["x"] = 1167,
			["w"] = 78,
			["h"] = 24,
		},
	},
	["player"] = {
		["buffgroup"] = {
			["y"] = -57,
			["h"] = 20,
			["count"] = 20,
			["hide"] = true,
			["x"] = 0,
			["rows"] = 2,
			["w"] = 20,
			["cols"] = 10,
		},
		["portrait"] = {
			["bgcolor"] = {
				["a"] = 0.4,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["show3d"] = true,
			["bordercolor"] = {
				["a"] = 0.777,
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["w"] = 50,
			["y"] = 0,
			["h"] = 50,
			["border"] = "Blizzard Tooltip",
			["x"] = -1,
			["bg"] = "Flat Smooth",
			["alpha"] = 1,
		},
		["debuffgroup"] = {
			["growth"] = "RLTB",
			["h"] = 36,
			["count"] = 6,
			["rows"] = 2,
			["w"] = 36,
			["cols"] = 6,
			["y"] = -70,
			["push"] = "None",
			["showpie"] = true,
			["spacing"] = 2,
			["counttfontflags"] = "OUTLINE",
			["vspacing"] = 1,
			["x"] = 215,
			["hide"] = true,
		},
		["runebar"] = {
			["y"] = 0,
			["x"] = 40,
			["bgcolor"] = {
				["a"] = 0.4,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["w"] = 38,
			["h"] = 6,
		},
		["text4"] = {
			["pattern"] = "[curmp]/[maxmp]   [percmp]%",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 169,
			["framelevel"] = 2,
			["y"] = -37,
			["x"] = 50,
			["fontsize"] = 12,
			["h"] = 12,
			["justifyH"] = "RIGHT",
			["justifyV"] = "BOTTOM",
		},
		["leadericon"] = {
			["y"] = 13,
			["x"] = 14,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["mpbar"] = {
			["baralpha"] = 1,
			["bgalpha"] = 0.3,
			["w"] = 170,
			["fade"] = true,
			["y"] = -38,
			["x"] = 51,
			["barcolormethod"] = "power",
			["h"] = 13,
			["bgcolormethod"] = "power",
			["framelevel"] = 1,
		},
		["druidbar"] = {
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bgalpha"] = 0.4,
			["w"] = 170,
			["bgcolormethod"] = "solid",
			["y"] = -48,
			["x"] = 50,
			["barcolormethod"] = "solid",
			["h"] = 3,
			["barcolor"] = {
				["r"] = 0.3,
				["g"] = 0.3,
				["b"] = 1,
			},
		},
		["text7"] = {
			["pattern"] = "",
			["w"] = 1,
			["framelevel"] = 2,
			["y"] = 0,
			["x"] = 0,
			["fontsize"] = 10,
			["justifyV"] = "CENTER",
			["h"] = 1,
			["justifyH"] = "CENTER",
			["hide"] = true,
		},
		["vehicleicon"] = {
			["y"] = -43,
			["x"] = -10,
			["hide"] = true,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["hpbar"] = {
			["baralpha"] = 1,
			["bgalpha"] = 1,
			["w"] = 170,
			["fade"] = true,
			["y"] = -18,
			["x"] = 51,
			["barcolormethod"] = "class",
			["h"] = 20,
			["bgcolormethod"] = "classdark",
			["inc"] = true,
			["framelevel"] = 1,
		},
		["combattext"] = {
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 52,
			["framelevel"] = 4,
			["y"] = -20,
			["x"] = 0,
			["fontsize"] = 12,
			["justifyV"] = "TOP",
			["h"] = 14,
			["justifyH"] = "CENTER",
			["hide"] = true,
		},
		["text3"] = {
			["pattern"] = "[curhp]/[maxhp]   [perchp]%",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 169,
			["framelevel"] = 2,
			["y"] = -21,
			["x"] = 50,
			["fontsize"] = 12,
			["fontflags"] = "None",
			["h"] = 12,
			["justifyH"] = "RIGHT",
			["justifyV"] = "BOTTOM",
		},
		["infoicon"] = {
			["y"] = 0,
			["x"] = 51,
			["h"] = 16,
			["w"] = 16,
			["framelevel"] = 2,
		},
		["totembar"] = {
			["y"] = -55,
			["x"] = 42,
			["bgcolor"] = {
				["a"] = 0.4,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["h"] = 14,
			["w"] = 32,
			["framelevel"] = 2,
		},
		["text6"] = {
			["pattern"] = "[gray_if_dead:死亡][gray_if_ghost:靈魂]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 200,
			["framelevel"] = 4,
			["y"] = -25,
			["x"] = 55,
			["fontsize"] = 20,
			["h"] = 20,
			["justifyH"] = "LEFT",
			["justifyV"] = "CENTER",
			["font"] = "傷害數字",
		},
		["lfgicon"] = {
			["y"] = -42,
			["h"] = 20,
			["circular"] = true,
			["x"] = 39,
			["alpha"] = 1,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["dispellicon"] = {
			["y"] = 0,
			["x"] = 54,
			["h"] = 50,
			["w"] = 50,
			["framelevel"] = 4,
		},
		["text1"] = {
			["pattern"] = "[name]",
			["shadowx"] = -1,
			["shadowy"] = -2,
			["w"] = 150,
			["framelevel"] = 2,
			["y"] = 0,
			["x"] = 70,
			["fontsize"] = 16,
			["h"] = 16,
			["fontflags"] = "None",
			["font"] = "傷害數字",
			["justifyH"] = "LEFT",
			["justifyV"] = "TOP",
		},
		["frame"] = {
			["y"] = -30,
			["x"] = 20,
			["bordercolormethod"] = "classdark",
			["w"] = 220,
			["h"] = 50,
		},
		["voiceicon"] = {
			["y"] = 7,
			["x"] = -8,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["text2"] = {
			["pattern"] = "[level] [class:race]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 150,
			["framelevel"] = 2,
			["y"] = 11,
			["x"] = 52,
			["fontsize"] = 11,
			["h"] = 12,
			["justifyH"] = "LEFT",
			["justifyV"] = "TOP",
		},
		["shardbar"] = {
			["y"] = -3,
			["x"] = 30,
		},
		["castbar"] = {
			["spellfontsize"] = 14,
			["bgcolor"] = {
				["a"] = 0.2,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["timeshadowy"] = -1,
			["spelljustifyH"] = "CENTER",
			["iconw"] = 20,
			["h"] = 52,
			["timefontsize"] = 12,
			["timeh"] = 12,
			["spellfontcolor"] = {
				["a"] = 0.7,
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.2,
			},
			["w"] = 220,
			["spelljustifyV"] = "CENTER",
			["y"] = 1,
			["x"] = 0,
			["iconx"] = 85,
			["timejustifyV"] = "CENTER",
			["spellw"] = 193,
			["baralpha"] = 0,
			["spellh"] = 14,
			["iconh"] = 20,
			["hide"] = true,
			["spellx"] = 5,
			["timey"] = -36,
			["timeshadowx"] = -1,
			["spelly"] = -38,
			["alpha"] = 1,
			["iconalpha"] = 0,
			["spellshadowy"] = -1,
			["timefontcolor"] = {
				["a"] = 0,
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.2,
			},
			["timew"] = 193,
			["spellshadowx"] = -1,
			["timejustifyH"] = "CENTER",
			["icony"] = -27,
			["timex"] = 0,
			["framelevel"] = 9,
		},
		["text5"] = {
			["pattern"] = "",
			["w"] = 100,
			["framelevel"] = 2,
			["y"] = -35,
			["x"] = 95,
			["fontsize"] = 10,
			["justifyV"] = "BOTTOM",
			["h"] = 10,
			["justifyH"] = "RIGHT",
			["hide"] = true,
		},
		["text8"] = {
			["pattern"] = "",
			["shadowx"] = -2,
			["shadowy"] = -1,
			["w"] = 100,
			["framelevel"] = 2,
			["y"] = -1,
			["x"] = 95,
			["fontsize"] = 16,
			["h"] = 30,
			["font"] = "傷害數字",
			["justifyH"] = "RIGHT",
			["justifyV"] = "CENTER",
			["hide"] = true,
		},
		["pvpicon"] = {
			["y"] = -12,
			["x"] = -12,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["tempenchant"] = {
			["timey"] = -2,
			["w"] = 36,
			["y"] = 4,
			["growth"] = "TBLR",
			["timefontsize"] = 8,
			["timew"] = 24,
			["x"] = 228,
			["count"] = 2,
			["h"] = 36,
			["timejustifyH"] = "LEFT",
			["timefontcolor"] = {
				["a"] = 0.9,
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["timex"] = 17,
			["alpha"] = 1,
		},
		["grouptext"] = {
			["bgcolor"] = {
				["a"] = 0.3,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 16,
			["framelevel"] = 3,
			["y"] = -2,
			["x"] = 32,
			["fontsize"] = 16,
			["h"] = 16,
			["justifyH"] = "CENTER",
			["justifyV"] = "CENTER",
		},
		["holybar"] = {
			["y"] = 3,
			["x"] = 0,
		},
		["priestbar"] = {
			["y"] = 0,
			["x"] = 0,
		},
		["looticon"] = {
			["y"] = -40,
			["x"] = -12,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["raidtargeticon"] = {
			["y"] = 12,
			["x"] = 193,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["eclipsebar"] = {
			["y"] = 0,
			["x"] = 0,
		},
		["chibar"] = {
			["y"] = 15,
			["x"] = 0,
		},
		["statusicon"] = {
			["y"] = -40,
			["x"] = -12,
			["h"] = 24,
			["w"] = 24,
			["framelevel"] = 4,
		},
	},
	["boss3target"] = {
		["frame"] = {
			["y"] = -436,
			["x"] = 1349,
			["w"] = 78,
			["h"] = 24,
		},
	},
	["partypet2"] = {
		["frame"] = {
			["y"] = -347,
			["x"] = 212,
		},
	},
	["partypet1"] = {
		["text2"] = {
			["y"] = 0,
			["h"] = 12,
			["pattern"] = "[perchp]",
			["fontsize"] = 9,
			["w"] = 24,
			["x"] = 25,
			["justifyV"] = "CENTER",
			["justifyH"] = "CENTER",
		},
		["portrait"] = {
			["y"] = 0,
			["x"] = 0,
			["h"] = 12,
			["w"] = 12,
			["hide"] = true,
		},
		["text3"] = {
			["y"] = 0,
			["x"] = 0,
			["pattern"] = "",
			["h"] = 10,
			["fontsize"] = 10,
			["w"] = 10,
			["hide"] = true,
		},
		["infoicon"] = {
			["y"] = 0,
			["h"] = 12,
			["x"] = 0,
			["w"] = 12,
			["hide"] = true,
		},
		["debuffgroup"] = {
			["rows"] = 1,
			["w"] = 6,
			["cols"] = 6,
			["y"] = -12,
			["push"] = "v",
			["count"] = 6,
			["h"] = 6,
			["x"] = 0,
			["hide"] = true,
		},
		["mpbar"] = {
			["y"] = -9,
			["h"] = 3,
			["hide"] = true,
			["barcolormethod"] = "power",
			["x"] = 12,
			["bgalpha"] = 0.3,
			["w"] = 24,
			["bgcolormethod"] = "powerdark",
		},
		["buffgroup"] = {
			["y"] = -12,
			["h"] = 6,
			["count"] = 6,
			["hide"] = true,
			["x"] = 0,
			["rows"] = 1,
			["w"] = 6,
			["cols"] = 6,
		},
		["text4"] = {
			["y"] = 0,
			["x"] = 0,
			["pattern"] = "",
			["h"] = 10,
			["fontsize"] = 10,
			["w"] = 10,
			["hide"] = true,
		},
		["raidtargeticon"] = {
			["y"] = 4,
			["h"] = 8,
			["x"] = 4,
			["w"] = 8,
			["hide"] = true,
		},
		["frame"] = {
			["y"] = -274,
			["x"] = 212,
			["w"] = 30,
			["h"] = 12,
		},
		["text1"] = {
			["pattern"] = "[name]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 24,
			["y"] = 0,
			["x"] = 14,
			["fontsize"] = 9,
			["justifyV"] = "TOP",
			["justifyH"] = "RIGHT",
			["h"] = 12,
			["hide"] = true,
		},
		["hpbar"] = {
			["baralpha"] = 1,
			["bgcolor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["barcolor"] = {
				["a"] = 1,
				["b"] = 0.31,
				["g"] = 0.31,
				["r"] = 0.31,
			},
			["w"] = 50,
			["bgcolormethod"] = "classdark",
			["y"] = 0,
			["h"] = 13,
			["barcolormethod"] = "class",
			["bgalpha"] = 1,
			["x"] = 0,
			["border"] = "Square Outline",
			["bordercolor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
		},
	},
	["targettargettarget"] = {
		["text2"] = {
			["pattern"] = "[difficulty:level][difficulty:classification]",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 70,
			["framelevel"] = 2,
			["y"] = 15,
			["x"] = 0,
			["fontsize"] = 12,
			["justifyH"] = "RIGHT",
			["justifyV"] = "TOP",
			["h"] = 12,
			["hide"] = true,
		},
		["portrait"] = {
			["zoom2d"] = true,
			["bgcolor"] = {
				["a"] = 0,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bordercolor"] = {
				["a"] = 0.777,
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["alpha"] = 1,
			["y"] = 2,
			["camera"] = 1,
			["w"] = 20,
			["h"] = 20,
			["border"] = "None",
			["x"] = -21,
			["bg"] = "Steel",
			["hide"] = true,
		},
		["text3"] = {
			["pattern"] = "[perchp]%",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 70,
			["framelevel"] = 2,
			["y"] = 0,
			["x"] = 0,
			["fontsize"] = 10,
			["h"] = 12,
			["fontflags"] = "None",
			["justifyV"] = "CENTER",
			["justifyH"] = "CENTER",
			["hide"] = true,
		},
		["infoicon"] = {
			["y"] = 2,
			["x"] = -21,
			["framelevel"] = 2,
			["h"] = 20,
			["w"] = 20,
			["hide"] = true,
		},
		["debuffgroup"] = {
			["w"] = 24,
			["x"] = 0,
			["showpie"] = true,
			["rows"] = 2,
			["growth"] = "LRTB",
			["cols"] = 5,
			["y"] = -55,
			["h"] = 24,
			["count"] = 5,
			["spacing"] = 2,
			["counttfontflags"] = "OUTLINE",
			["vspacing"] = 1,
			["push"] = "None",
			["hide"] = true,
		},
		["mpbar"] = {
			["baralpha"] = 1,
			["bartexture"] = "Flat Smooth",
			["x"] = 0,
			["bgalpha"] = 0,
			["border"] = "Square Outline",
			["framelevel"] = 1,
			["y"] = -12,
			["h"] = 5,
			["w"] = 70,
			["barcolormethod"] = "power",
			["bordercolor"] = {
				["a"] = 0,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["fade"] = true,
			["bgcolormethod"] = "powerdark",
			["hide"] = true,
		},
		["hpbar"] = {
			["baralpha"] = 1,
			["bartexture"] = "Flat Smooth",
			["bgalpha"] = 0.3,
			["bordercolor"] = {
				["a"] = 0.645,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["border"] = "Square Outline",
			["bgcolormethod"] = "hpgreendark",
			["y"] = 0,
			["x"] = 0,
			["w"] = 70,
			["barcolormethod"] = "hpgreen",
			["fade"] = true,
			["h"] = 10,
			["inc"] = true,
			["framelevel"] = 1,
		},
		["text4"] = {
			["pattern"] = "[curmp]",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 70,
			["framelevel"] = 2,
			["y"] = -12,
			["x"] = 0,
			["fontsize"] = 10,
			["justifyV"] = "CENTER",
			["h"] = 12,
			["justifyH"] = "CENTER",
			["hide"] = true,
		},
		["raidtargeticon"] = {
			["y"] = 40,
			["x"] = 0,
			["framelevel"] = 4,
			["h"] = 20,
			["w"] = 20,
			["hide"] = true,
		},
		["frame"] = {
			["y"] = -50,
			["x"] = 865,
			["bordercolormethod"] = "solid",
			["h"] = 14,
			["bordercolor"] = {
				["a"] = 0,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["w"] = 70,
			["hide"] = true,
		},
		["text1"] = {
			["pattern"] = "[name]",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 75,
			["framelevel"] = 2,
			["y"] = 16,
			["font"] = "預設",
			["fontsize"] = 12,
			["x"] = 0,
			["fontflags"] = "None",
			["justifyV"] = "TOP",
			["justifyH"] = "LEFT",
			["h"] = 16,
		},
		["buffgroup"] = {
			["timeonlymine"] = true,
			["pieonlymine"] = true,
			["rows"] = 2,
			["w"] = 20,
			["cols"] = 7,
			["y"] = -28,
			["x"] = 0,
			["count"] = 5,
			["spacing"] = 2,
			["timefontsize"] = 1,
			["vspacing"] = 5,
			["h"] = 20,
			["hide"] = true,
		},
	},
	["party4target"] = {
		["frame"] = {
			["y"] = -444,
			["x"] = 211,
		},
	},
	["arena3target"] = {
		["frame"] = {
			["y"] = -421,
			["h"] = 24,
			["x"] = 1243,
			["w"] = 78,
			["hide"] = true,
		},
	},
	["arenapet5"] = {
		["frame"] = {
			["y"] = -527,
			["h"] = 24,
			["x"] = 1127,
			["w"] = 78,
			["hide"] = true,
		},
	},
	["party2target"] = {
		["frame"] = {
			["y"] = -302,
			["x"] = 212,
		},
	},
	["party2"] = {
		["frame"] = {
			["y"] = -380,
			["x"] = 41,
		},
	},
	["focus"] = {
		["buffgroup"] = {
			["y"] = -28,
			["h"] = 17,
			["count"] = 7,
			["x"] = 0,
			["growth"] = "LRTB",
			["rows"] = 2,
			["w"] = 17,
			["cols"] = 16,
		},
		["portrait"] = {
			["y"] = -1,
			["h"] = 48,
			["bgcolor"] = {
				["a"] = 0.4,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["show3d"] = true,
			["x"] = 1,
			["bg"] = "Flat Smooth",
			["w"] = 48,
			["hide"] = true,
		},
		["combattext"] = {
			["y"] = 1,
			["h"] = 12,
			["justifyH"] = "CENTER",
			["x"] = -1,
			["w"] = 40,
			["fontsize"] = 10,
			["justifyV"] = "TOP",
			["hide"] = true,
		},
		["text3"] = {
			["pattern"] = "[perchp]%",
			["w"] = 140,
			["y"] = -8,
			["h"] = 21,
			["fontsize"] = 14,
			["emptyhide"] = true,
			["justifyH"] = "LEFT",
			["x"] = 72,
			["justifyV"] = "TOP",
		},
		["infoicon"] = {
			["y"] = -37,
			["x"] = 50,
			["h"] = 12,
			["w"] = 12,
			["hide"] = true,
		},
		["debuffgroup"] = {
			["rows"] = 2,
			["w"] = 40,
			["cols"] = 8,
			["y"] = -30,
			["x"] = 0,
			["count"] = 10,
			["spacing"] = 2,
			["growth"] = "TBLR",
			["vspacing"] = 1,
			["push"] = "v",
			["h"] = 40,
		},
		["text6"] = {
			["y"] = -21,
			["x"] = 1,
			["pattern"] = "[gray_if_dead:DEAD]",
			["justifyH"] = "CENTER",
			["justifyV"] = "CENTER",
			["h"] = 10,
			["w"] = 145,
			["fontsize"] = 10,
		},
		["text1"] = {
			["pattern"] = "[name]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 140,
			["y"] = 10,
			["x"] = 3,
			["fontsize"] = 14,
			["fontflags"] = "OUTLINE",
			["justifyH"] = "LEFT",
			["h"] = 14,
			["justifyV"] = "TOP",
		},
		["threatbar"] = {
			["y"] = 12,
			["x"] = 10,
			["bgcolor"] = {
				["a"] = 0.4,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["h"] = 12,
			["w"] = 32,
			["hide"] = true,
		},
		["happinessicon"] = {
			["y"] = -2,
			["x"] = -15,
			["h"] = 16,
			["w"] = 16,
			["framelevel"] = 5,
		},
		["text2"] = {
			["onmouse"] = true,
			["pattern"] = "[level]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 140,
			["y"] = 8,
			["x"] = -140,
			["fontsize"] = 12,
			["h"] = 12,
			["justifyV"] = "TOP",
			["justifyH"] = "RIGHT",
		},
		["dispellicon"] = {
			["y"] = -4,
			["x"] = 149,
			["h"] = 42,
			["w"] = 42,
			["hide"] = true,
		},
		["castbar"] = {
			["baralpha"] = 0,
			["spellfontsize"] = 12,
			["spellshadowy"] = -1,
			["spellh"] = 12,
			["spelljustifyH"] = "CENTER",
			["iconh"] = 12,
			["iconw"] = 12,
			["h"] = 40,
			["alpha"] = 1,
			["icony"] = -26,
			["iconhide"] = true,
			["timefontsize"] = 10,
			["timefontcolor"] = {
				["a"] = 0,
				["b"] = 0.2,
				["g"] = 0.5,
				["r"] = 1,
			},
			["timejustifyV"] = "CENTER",
			["iconx"] = 62,
			["timew"] = 147,
			["spellx"] = 0,
			["timey"] = -30,
			["timeh"] = 10,
			["spellfontcolor"] = {
				["a"] = 0.7,
				["b"] = 0.2,
				["g"] = 0.5,
				["r"] = 1,
			},
			["w"] = 147,
			["spelljustifyV"] = "CENTER",
			["y"] = 1,
			["x"] = -1,
			["spelly"] = -18,
			["spellshadowx"] = -1,
			["timejustifyH"] = "CENTER",
			["spellw"] = 147,
			["timex"] = 0,
			["bgcolor"] = {
				["a"] = 0.2,
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
		},
		["text5"] = {
			["y"] = -24,
			["x"] = -130,
			["pattern"] = "[percmp]%",
			["fontsize"] = 10,
			["w"] = 140,
			["justifyH"] = "RIGHT",
			["justifyV"] = "BOTTOM",
			["h"] = 10,
		},
		["text4"] = {
			["onmouse"] = true,
			["pattern"] = "[curhp]",
			["w"] = 126,
			["y"] = -8,
			["h"] = 10,
			["fontsize"] = 10,
			["emptyhide"] = true,
			["justifyH"] = "RIGHT",
			["x"] = -80,
			["justifyV"] = "BOTTOM",
		},
		["pvpicon"] = {
			["y"] = -5,
			["x"] = -8,
			["h"] = 16,
			["w"] = 16,
			["hide"] = true,
		},
		["hpbar"] = {
			["bgcolor"] = {
				["a"] = 1,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bgalpha"] = 1,
			["w"] = 100,
			["fade"] = true,
			["y"] = 0,
			["x"] = 0,
			["barcolor"] = {
				["a"] = 1,
				["r"] = 0.302,
				["g"] = 0.302,
				["b"] = 0.302,
			},
			["barcolormethod"] = "class",
			["h"] = 20,
			["bgcolormethod"] = "classdark",
			["border"] = "Square Outline",
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
		},
		["pettime"] = {
			["y"] = -25,
			["h"] = 10,
			["fontsize"] = 10,
			["x"] = 0,
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 36,
			["hide"] = true,
		},
		["mpbar"] = {
			["baralpha"] = 1,
			["bgcolor"] = {
				["a"] = 1,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 0.012,
				["g"] = 0.012,
				["b"] = 0.012,
			},
			["w"] = 110,
			["fade"] = true,
			["y"] = -12,
			["h"] = 15,
			["framelevel"] = 0,
			["barcolormethod"] = "power",
			["x"] = -5,
			["bgcolormethod"] = "powerdark",
			["border"] = "Square Outline",
			["bgalpha"] = 1,
		},
		["auratimers"] = {
			["rows"] = 4,
			["w"] = 50,
			["cols"] = 1,
			["y"] = -24,
			["x"] = 0,
			["count"] = 4,
			["h"] = 12,
			["growth"] = "TBLR",
			["push"] = "v",
			["hide"] = true,
		},
		["rangetext"] = {
			["y"] = 10,
			["x"] = 72,
			["fontsize"] = 10,
			["justifyH"] = "CENTER",
			["w"] = 50,
			["h"] = 10,
		},
		["raidtargeticon"] = {
			["y"] = -15,
			["h"] = 16,
			["x"] = 195,
			["w"] = 16,
			["hide"] = true,
		},
		["frame"] = {
			["y"] = -603,
			["h"] = 20,
			["bordercolor"] = {
				["a"] = 0,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["w"] = 100,
			["x"] = 583,
		},
		["comboframe"] = {
			["y"] = -24,
			["x"] = 14,
			["w"] = 55,
			["glowcolor"] = {
				["a"] = 0.8,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["h"] = 47,
			["combostyle"] = 2,
			["color"] = {
				["a"] = 1,
				["r"] = 0.7,
				["g"] = 0,
				["b"] = 0,
			},
		},
		["statusicon"] = {
			["y"] = 5,
			["x"] = -10,
			["h"] = 14,
			["w"] = 14,
			["hide"] = true,
		},
	},
	["arena2"] = {
		["frame"] = {
			["y"] = -374,
			["h"] = 24,
			["x"] = 1164,
			["w"] = 78,
			["hide"] = true,
		},
	},
	["boss1target"] = {
		["text2"] = {
			["pattern"] = "",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 200,
			["framelevel"] = 2,
			["y"] = 18,
			["x"] = 0,
			["fontsize"] = 12,
			["justifyV"] = "TOP",
			["justifyH"] = "RIGHT",
			["h"] = 12,
			["hide"] = true,
		},
		["portrait"] = {
			["bgcolor"] = {
				["a"] = 0,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["bordercolor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0.855,
				["r"] = 1,
			},
			["alpha"] = 1,
			["y"] = 18,
			["camera"] = 1,
			["w"] = 60,
			["border"] = "None",
			["h"] = 60,
			["x"] = -64,
			["bg"] = "Steel",
			["hide"] = true,
		},
		["text3"] = {
			["pattern"] = "[perchp]%",
			["font"] = "傷害數字",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 80,
			["framelevel"] = 2,
			["y"] = -5,
			["x"] = 0,
			["fontsize"] = 14,
			["justifyH"] = "CENTER",
			["fontflags"] = "OUTLINE",
			["justifyV"] = "TOP",
			["h"] = 20,
			["hide"] = true,
		},
		["infoicon"] = {
			["y"] = 12,
			["x"] = -35,
			["circular"] = true,
			["hide"] = true,
			["h"] = 30,
			["w"] = 30,
			["framelevel"] = 2,
		},
		["debuffgroup"] = {
			["w"] = 30,
			["count"] = 7,
			["counttfontflags"] = "OUTLINE",
			["rows"] = 1,
			["growth"] = "LRBT",
			["cols"] = 10,
			["y"] = -10,
			["x"] = 185,
			["showpie"] = true,
			["spacing"] = 2,
			["push"] = "None",
			["vspacing"] = 1,
			["h"] = 30,
			["hide"] = true,
		},
		["mpbar"] = {
			["baralpha"] = 1,
			["bartexture"] = "Blizzard",
			["w"] = 80,
			["bgalpha"] = 0.3,
			["border"] = "Blizzard Tooltip",
			["framelevel"] = 1,
			["y"] = 0,
			["h"] = 6,
			["x"] = 95,
			["barcolormethod"] = "power",
			["bgcolormethod"] = "powerdark",
			["fade"] = true,
			["bordercolor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0.918,
				["r"] = 1,
			},
			["hide"] = true,
		},
		["hpbar"] = {
			["baralpha"] = 1,
			["bgcolor"] = {
				["a"] = 0,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["bartexture"] = "Blizzard",
			["framelevel"] = 1,
			["bordercolor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0.796,
				["r"] = 1,
			},
			["border"] = "None",
			["bgcolormethod"] = "classdark",
			["y"] = 1,
			["x"] = 0,
			["w"] = 80,
			["barcolormethod"] = "classreaction",
			["h"] = 10,
			["fade"] = true,
			["inc"] = true,
			["bgalpha"] = 0.3,
		},
		["buffgroup"] = {
			["timey"] = 0,
			["rows"] = 1,
			["w"] = 20,
			["cols"] = 10,
			["y"] = 8,
			["x"] = 185,
			["count"] = 5,
			["spacing"] = 2,
			["vspacing"] = 5,
			["h"] = 20,
			["hide"] = true,
		},
		["raidtargeticon"] = {
			["y"] = 10,
			["x"] = -33,
			["hide"] = true,
			["h"] = 26,
			["w"] = 26,
			["framelevel"] = 6,
		},
		["frame"] = {
			["y"] = -320,
			["h"] = 6,
			["bordercolormethod"] = "classreaction",
			["bordercolor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0.906,
				["r"] = 1,
			},
			["w"] = 80,
			["x"] = 1349,
		},
		["text1"] = {
			["pattern"] = "[classreaction:name]",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["justifyV"] = "TOP",
			["framelevel"] = 2,
			["y"] = 18,
			["x"] = 0,
			["fontsize"] = 14,
			["w"] = 200,
			["fontflags"] = "None",
			["font"] = "預設",
			["h"] = 16,
			["justifyH"] = "LEFT",
		},
		["text4"] = {
			["pattern"] = "[curmp]",
			["w"] = 80,
			["shadowx"] = 1,
			["shadowy"] = -1,
			["justifyV"] = "TOP",
			["framelevel"] = 2,
			["y"] = -5,
			["x"] = 95,
			["fontsize"] = 14,
			["justifyH"] = "CENTER",
			["fontflags"] = "OUTLINE",
			["h"] = 20,
			["font"] = "傷害數字",
			["hide"] = true,
		},
	},
	["partypet3"] = {
		["frame"] = {
			["y"] = -420,
			["x"] = 212,
		},
	},
	["party4"] = {
		["frame"] = {
			["y"] = -558,
			["x"] = 38,
		},
	},
	["arena5"] = {
		["frame"] = {
			["y"] = -515,
			["h"] = 24,
			["x"] = 1164,
			["w"] = 78,
			["hide"] = true,
		},
	},
	["party3target"] = {
		["frame"] = {
			["y"] = -372,
			["x"] = 212,
		},
	},
	["boss5"] = {
		["frame"] = {
			["y"] = -574,
			["x"] = 1167,
			["w"] = 78,
			["h"] = 24,
		},
	},
	["boss2target"] = {
		["frame"] = {
			["y"] = -378,
			["x"] = 1349,
			["w"] = 78,
			["h"] = 24,
		},
	},
	["arena1target"] = {
		["text2"] = {
			["y"] = -11,
			["x"] = 1,
			["pattern"] = "",
			["h"] = 10,
			["w"] = 108,
			["hide"] = true,
		},
		["portrait"] = {
			["y"] = 0,
			["x"] = 55,
			["w"] = 24,
			["h"] = 24,
		},
		["text3"] = {
			["y"] = -13,
			["x"] = 1,
			["pattern"] = "[perchp]%",
			["h"] = 10,
			["w"] = 54,
			["fontsize"] = 10,
			["justifyV"] = "CENTER",
			["justifyH"] = "CENTER",
		},
		["infoicon"] = {
			["y"] = 0,
			["x"] = 0,
			["h"] = 12,
			["w"] = 12,
			["hide"] = true,
		},
		["debuffgroup"] = {
			["rows"] = 1,
			["w"] = 10,
			["cols"] = 8,
			["y"] = -23,
			["x"] = 0,
			["count"] = 8,
			["push"] = "v",
			["h"] = 10,
			["growth"] = "LRTB",
			["hide"] = true,
		},
		["mpbar"] = {
			["y"] = -19,
			["x"] = 1,
			["h"] = 5,
			["barcolormethod"] = "power",
			["reverse"] = true,
			["bgalpha"] = 0.3,
			["w"] = 53,
			["bgcolormethod"] = "powerdark",
		},
		["hpbar"] = {
			["y"] = -1,
			["x"] = 1,
			["h"] = 17,
			["barcolormethod"] = "hpgreen",
			["reverse"] = true,
			["bgalpha"] = 0.3,
			["w"] = 53,
			["bgcolormethod"] = "hpgreendark",
		},
		["text4"] = {
			["y"] = -24,
			["x"] = 1,
			["pattern"] = "",
			["h"] = 10,
			["w"] = 54,
			["hide"] = true,
		},
		["frame"] = {
			["y"] = -327,
			["h"] = 24,
			["x"] = 1243,
			["w"] = 78,
			["hide"] = true,
		},
		["text1"] = {
			["pattern"] = "[reaction:*][class:name]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 54,
			["y"] = 0,
			["x"] = 1,
			["fontsize"] = 12,
			["h"] = 12,
			["justifyH"] = "RIGHT",
			["justifyV"] = "TOP",
		},
		["buffgroup"] = {
			["rows"] = 1,
			["w"] = 10,
			["cols"] = 8,
			["y"] = -24,
			["x"] = 0,
			["count"] = 8,
			["growth"] = "LRTB",
			["h"] = 10,
			["hide"] = true,
		},
	},
	["arenapet3"] = {
		["frame"] = {
			["y"] = -433,
			["h"] = 24,
			["x"] = 1127,
			["w"] = 78,
			["hide"] = true,
		},
	},
	["pettarget"] = {
		["buffgroup"] = {
			["rows"] = 2,
			["w"] = 17,
			["cols"] = 16,
			["y"] = -52,
			["h"] = 17,
			["count"] = 32,
			["growth"] = "LRTB",
			["x"] = 0,
			["hide"] = true,
		},
		["portrait"] = {
			["y"] = -1,
			["h"] = 48,
			["bgcolor"] = {
				["a"] = 0.4,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["show3d"] = true,
			["x"] = 1,
			["w"] = 48,
			["bg"] = "Flat Smooth",
			["hide"] = true,
		},
		["combattext"] = {
			["y"] = 1,
			["h"] = 12,
			["justifyH"] = "CENTER",
			["x"] = -1,
			["justifyV"] = "TOP",
			["fontsize"] = 10,
			["w"] = 40,
			["hide"] = true,
		},
		["text3"] = {
			["pattern"] = "[perchp]%",
			["w"] = 140,
			["y"] = -8,
			["h"] = 21,
			["fontsize"] = 14,
			["emptyhide"] = true,
			["justifyV"] = "TOP",
			["x"] = 72,
			["justifyH"] = "LEFT",
		},
		["infoicon"] = {
			["y"] = -37,
			["x"] = 50,
			["h"] = 12,
			["w"] = 12,
			["hide"] = true,
		},
		["debuffgroup"] = {
			["rows"] = 3,
			["w"] = 17,
			["cols"] = 16,
			["y"] = -52,
			["push"] = "v",
			["count"] = 40,
			["growth"] = "TBLR",
			["h"] = 17,
			["x"] = 0,
			["hide"] = true,
		},
		["text6"] = {
			["y"] = -21,
			["x"] = 1,
			["pattern"] = "[gray_if_dead:DEAD]",
			["fontsize"] = 10,
			["w"] = 145,
			["h"] = 10,
			["justifyV"] = "CENTER",
			["justifyH"] = "CENTER",
		},
		["text1"] = {
			["pattern"] = "[name]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 140,
			["y"] = 10,
			["x"] = 3,
			["fontsize"] = 14,
			["fontflags"] = "OUTLINE",
			["h"] = 14,
			["justifyH"] = "LEFT",
			["justifyV"] = "TOP",
		},
		["text2"] = {
			["onmouse"] = true,
			["pattern"] = "[level]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 140,
			["y"] = 8,
			["x"] = -140,
			["fontsize"] = 12,
			["justifyH"] = "RIGHT",
			["justifyV"] = "TOP",
			["h"] = 12,
		},
		["castbar"] = {
			["baralpha"] = 0,
			["spellfontsize"] = 12,
			["spellshadowy"] = -1,
			["spellh"] = 12,
			["spelljustifyH"] = "CENTER",
			["bgcolor"] = {
				["a"] = 0.2,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["iconh"] = 12,
			["iconw"] = 12,
			["h"] = 40,
			["spelljustifyV"] = "CENTER",
			["spellw"] = 147,
			["iconhide"] = true,
			["timefontsize"] = 10,
			["timejustifyH"] = "CENTER",
			["hide"] = true,
			["spellshadowx"] = -1,
			["spelly"] = -18,
			["spellx"] = 0,
			["timey"] = -30,
			["timeh"] = 10,
			["spellfontcolor"] = {
				["a"] = 0.7,
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.2,
			},
			["alpha"] = 1,
			["icony"] = -26,
			["timew"] = 147,
			["x"] = -1,
			["y"] = 1,
			["iconx"] = 62,
			["timejustifyV"] = "CENTER",
			["timefontcolor"] = {
				["a"] = 0,
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.2,
			},
			["timex"] = 0,
			["w"] = 147,
		},
		["text5"] = {
			["y"] = -24,
			["x"] = -130,
			["pattern"] = "[percmp]%",
			["h"] = 10,
			["justifyV"] = "BOTTOM",
			["justifyH"] = "RIGHT",
			["w"] = 140,
			["fontsize"] = 10,
		},
		["dispellicon"] = {
			["y"] = -4,
			["x"] = 149,
			["h"] = 42,
			["w"] = 42,
			["hide"] = true,
		},
		["text4"] = {
			["onmouse"] = true,
			["pattern"] = "[curhp]",
			["w"] = 126,
			["y"] = -8,
			["h"] = 10,
			["fontsize"] = 10,
			["emptyhide"] = true,
			["justifyV"] = "BOTTOM",
			["x"] = -80,
			["justifyH"] = "RIGHT",
		},
		["mpbar"] = {
			["baralpha"] = 1,
			["bgcolor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["bordercolor"] = {
				["a"] = 1,
				["b"] = 0.012,
				["g"] = 0.012,
				["r"] = 0.012,
			},
			["w"] = 110,
			["fade"] = true,
			["y"] = -12,
			["h"] = 15,
			["bgalpha"] = 1,
			["barcolormethod"] = "power",
			["border"] = "Square Outline",
			["bgcolormethod"] = "powerdark",
			["x"] = -5,
			["framelevel"] = 0,
		},
		["pettime"] = {
			["y"] = -25,
			["h"] = 10,
			["fontsize"] = 10,
			["x"] = 0,
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 36,
			["hide"] = true,
		},
		["hpbar"] = {
			["bgcolor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["bgalpha"] = 1,
			["w"] = 100,
			["fade"] = true,
			["y"] = 0,
			["x"] = 0,
			["bordercolor"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["barcolormethod"] = "class",
			["border"] = "Square Outline",
			["bgcolormethod"] = "classdark",
			["h"] = 20,
			["barcolor"] = {
				["a"] = 1,
				["b"] = 0.302,
				["g"] = 0.302,
				["r"] = 0.302,
			},
		},
		["raidtargeticon"] = {
			["y"] = -15,
			["h"] = 16,
			["x"] = 195,
			["w"] = 16,
			["hide"] = true,
		},
		["frame"] = {
			["y"] = -118,
			["h"] = 20,
			["bordercolor"] = {
				["a"] = 0,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["w"] = 100,
			["x"] = 172,
		},
		["happinessicon"] = {
			["y"] = -2,
			["x"] = -15,
			["h"] = 16,
			["w"] = 16,
			["framelevel"] = 5,
		},
		["statusicon"] = {
			["y"] = 5,
			["x"] = -10,
			["h"] = 14,
			["w"] = 14,
			["hide"] = true,
		},
	},
	["focustarget"] = {
		["buffgroup"] = {
			["rows"] = 2,
			["w"] = 17,
			["cols"] = 16,
			["y"] = -52,
			["h"] = 17,
			["count"] = 32,
			["growth"] = "LRTB",
			["x"] = 0,
			["hide"] = true,
		},
		["portrait"] = {
			["y"] = -1,
			["h"] = 48,
			["bgcolor"] = {
				["a"] = 0.4,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["show3d"] = true,
			["x"] = 1,
			["bg"] = "Flat Smooth",
			["w"] = 48,
			["hide"] = true,
		},
		["combattext"] = {
			["y"] = 1,
			["h"] = 12,
			["justifyH"] = "CENTER",
			["x"] = -1,
			["w"] = 40,
			["fontsize"] = 10,
			["justifyV"] = "TOP",
			["hide"] = true,
		},
		["text3"] = {
			["pattern"] = "[perchp]%",
			["w"] = 140,
			["y"] = -8,
			["h"] = 21,
			["fontsize"] = 14,
			["emptyhide"] = true,
			["justifyH"] = "LEFT",
			["x"] = 72,
			["justifyV"] = "TOP",
		},
		["infoicon"] = {
			["y"] = -37,
			["x"] = 50,
			["h"] = 12,
			["w"] = 12,
			["hide"] = true,
		},
		["debuffgroup"] = {
			["rows"] = 3,
			["w"] = 17,
			["cols"] = 16,
			["y"] = -52,
			["push"] = "v",
			["count"] = 40,
			["growth"] = "TBLR",
			["x"] = 0,
			["h"] = 17,
			["hide"] = true,
		},
		["text6"] = {
			["y"] = -21,
			["x"] = 1,
			["pattern"] = "[gray_if_dead:DEAD]",
			["justifyH"] = "CENTER",
			["justifyV"] = "CENTER",
			["h"] = 10,
			["w"] = 145,
			["fontsize"] = 10,
		},
		["text1"] = {
			["pattern"] = "[name]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 140,
			["y"] = 10,
			["x"] = 3,
			["fontsize"] = 14,
			["fontflags"] = "OUTLINE",
			["justifyV"] = "TOP",
			["justifyH"] = "LEFT",
			["h"] = 14,
		},
		["text2"] = {
			["onmouse"] = true,
			["pattern"] = "[level]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 140,
			["y"] = 8,
			["x"] = -140,
			["fontsize"] = 12,
			["h"] = 12,
			["justifyV"] = "TOP",
			["justifyH"] = "RIGHT",
		},
		["castbar"] = {
			["baralpha"] = 0,
			["spellfontsize"] = 12,
			["spellshadowy"] = -1,
			["spellh"] = 12,
			["spelljustifyH"] = "CENTER",
			["alpha"] = 1,
			["iconh"] = 12,
			["iconw"] = 12,
			["h"] = 40,
			["icony"] = -26,
			["timefontcolor"] = {
				["a"] = 0,
				["b"] = 0.2,
				["g"] = 0.5,
				["r"] = 1,
			},
			["iconhide"] = true,
			["timefontsize"] = 10,
			["timejustifyV"] = "CENTER",
			["hide"] = true,
			["iconx"] = 62,
			["timew"] = 147,
			["spellx"] = 0,
			["timey"] = -30,
			["timeh"] = 10,
			["spellfontcolor"] = {
				["a"] = 0.7,
				["b"] = 0.2,
				["g"] = 0.5,
				["r"] = 1,
			},
			["w"] = 147,
			["spelljustifyV"] = "CENTER",
			["y"] = 1,
			["x"] = -1,
			["spelly"] = -18,
			["spellshadowx"] = -1,
			["timejustifyH"] = "CENTER",
			["spellw"] = 147,
			["timex"] = 0,
			["bgcolor"] = {
				["a"] = 0.2,
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
		},
		["text5"] = {
			["y"] = -24,
			["x"] = -130,
			["pattern"] = "[percmp]%",
			["fontsize"] = 10,
			["w"] = 140,
			["justifyH"] = "RIGHT",
			["justifyV"] = "BOTTOM",
			["h"] = 10,
		},
		["dispellicon"] = {
			["y"] = -4,
			["x"] = 149,
			["h"] = 42,
			["w"] = 42,
			["hide"] = true,
		},
		["happinessicon"] = {
			["y"] = -2,
			["x"] = -15,
			["h"] = 16,
			["w"] = 16,
			["framelevel"] = 5,
		},
		["mpbar"] = {
			["baralpha"] = 1,
			["bgcolor"] = {
				["a"] = 1,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 0.012,
				["g"] = 0.012,
				["b"] = 0.012,
			},
			["w"] = 110,
			["fade"] = true,
			["y"] = -12,
			["h"] = 15,
			["framelevel"] = 0,
			["barcolormethod"] = "power",
			["x"] = -5,
			["bgcolormethod"] = "powerdark",
			["border"] = "Square Outline",
			["bgalpha"] = 1,
		},
		["pettime"] = {
			["y"] = -25,
			["h"] = 10,
			["fontsize"] = 10,
			["x"] = 0,
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 36,
			["hide"] = true,
		},
		["hpbar"] = {
			["bgcolor"] = {
				["a"] = 1,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bgalpha"] = 1,
			["w"] = 100,
			["fade"] = true,
			["y"] = 0,
			["x"] = 0,
			["barcolor"] = {
				["a"] = 1,
				["r"] = 0.302,
				["g"] = 0.302,
				["b"] = 0.302,
			},
			["barcolormethod"] = "class",
			["h"] = 20,
			["bgcolormethod"] = "classdark",
			["border"] = "Square Outline",
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
		},
		["raidtargeticon"] = {
			["y"] = -15,
			["h"] = 16,
			["x"] = 195,
			["w"] = 16,
			["hide"] = true,
		},
		["frame"] = {
			["y"] = -546,
			["h"] = 20,
			["bordercolor"] = {
				["a"] = 0,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["w"] = 100,
			["x"] = 585,
		},
		["text4"] = {
			["onmouse"] = true,
			["pattern"] = "[curhp]",
			["w"] = 126,
			["y"] = -8,
			["h"] = 10,
			["fontsize"] = 10,
			["emptyhide"] = true,
			["justifyH"] = "RIGHT",
			["x"] = -80,
			["justifyV"] = "BOTTOM",
		},
		["statusicon"] = {
			["y"] = 5,
			["x"] = -10,
			["h"] = 14,
			["w"] = 14,
			["hide"] = true,
		},
	},
	["targettarget"] = {
		["text2"] = {
			["pattern"] = "[perchp]%",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 200,
			["framelevel"] = 2,
			["y"] = 12,
			["x"] = -34,
			["fontsize"] = 12,
			["justifyH"] = "RIGHT",
			["h"] = 16,
			["justifyV"] = "TOP",
		},
		["portrait"] = {
			["bgcolor"] = {
				["a"] = 0,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 1,
				["g"] = 0.855,
				["b"] = 0,
			},
			["w"] = 60,
			["y"] = 18,
			["x"] = -64,
			["alpha"] = 1,
			["camera"] = 1,
			["h"] = 60,
			["border"] = "None",
			["bg"] = "Steel",
			["hide"] = true,
		},
		["text4"] = {
			["pattern"] = "[curmp]",
			["justifyH"] = "CENTER",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 160,
			["framelevel"] = 2,
			["y"] = -5,
			["x"] = 180,
			["fontsize"] = 20,
			["font"] = "傷害數字",
			["fontflags"] = "OUTLINE",
			["h"] = 20,
			["justifyV"] = "TOP",
			["hide"] = true,
		},
		["infoicon"] = {
			["y"] = 12,
			["x"] = -35,
			["circular"] = true,
			["hide"] = true,
			["h"] = 30,
			["w"] = 30,
			["framelevel"] = 2,
		},
		["text3"] = {
			["pattern"] = "[perchp]%",
			["x"] = 0,
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 160,
			["framelevel"] = 2,
			["y"] = -5,
			["font"] = "傷害數字",
			["fontsize"] = 20,
			["justifyH"] = "CENTER",
			["fontflags"] = "OUTLINE",
			["justifyV"] = "TOP",
			["h"] = 20,
			["hide"] = true,
		},
		["pvpicon"] = {
			["y"] = -36,
			["x"] = 290,
			["framelevel"] = 4,
			["h"] = 30,
			["w"] = 30,
			["hide"] = true,
		},
		["debuffgroup"] = {
			["growth"] = "LRBT",
			["x"] = 5,
			["showpie"] = true,
			["rows"] = 2,
			["w"] = 30,
			["cols"] = 10,
			["y"] = 30,
			["h"] = 30,
			["count"] = 20,
			["spacing"] = 2,
			["counttfontflags"] = "OUTLINE",
			["vspacing"] = 1,
			["push"] = "None",
			["hide"] = true,
		},
		["dispellicon"] = {
			["y"] = 25,
			["x"] = 130,
			["framelevel"] = 4,
			["h"] = 36,
			["w"] = 36,
			["hide"] = true,
		},
		["mpbar"] = {
			["baralpha"] = 1,
			["bartexture"] = "Blizzard",
			["h"] = 10,
			["bgalpha"] = 0.3,
			["border"] = "Blizzard Tooltip",
			["framelevel"] = 1,
			["y"] = 0,
			["x"] = 180,
			["bgcolormethod"] = "powerdark",
			["barcolormethod"] = "power",
			["fade"] = true,
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 1,
				["g"] = 0.918,
				["b"] = 0,
			},
			["w"] = 160,
			["hide"] = true,
		},
		["hpbar"] = {
			["baralpha"] = 1,
			["bgcolor"] = {
				["a"] = 0,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["bartexture"] = "Blizzard",
			["bgcolormethod"] = "classdark",
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 1,
				["g"] = 0.796,
				["b"] = 0,
			},
			["border"] = "None",
			["framelevel"] = 1,
			["y"] = 1,
			["x"] = 0,
			["w"] = 160,
			["barcolormethod"] = "classreaction",
			["h"] = 12,
			["fade"] = true,
			["inc"] = true,
			["bgalpha"] = 0.3,
		},
		["buffgroup"] = {
			["timey"] = 0,
			["rows"] = 3,
			["w"] = 20,
			["cols"] = 7,
			["y"] = -39,
			["x"] = 5,
			["count"] = 21,
			["spacing"] = 2,
			["vspacing"] = 5,
			["h"] = 20,
			["hide"] = true,
		},
		["raidtargeticon"] = {
			["y"] = 10,
			["x"] = -33,
			["hide"] = true,
			["h"] = 26,
			["w"] = 26,
			["framelevel"] = 6,
		},
		["frame"] = {
			["y"] = -51,
			["h"] = 10,
			["bordercolormethod"] = "classreaction",
			["bordercolor"] = {
				["a"] = 1,
				["r"] = 1,
				["g"] = 0.906,
				["b"] = 0,
			},
			["w"] = 160,
			["x"] = 775,
		},
		["text1"] = {
			["pattern"] = "[classreaction:name]",
			["shadowx"] = 1,
			["shadowy"] = -1,
			["w"] = 200,
			["framelevel"] = 2,
			["y"] = 18,
			["h"] = 16,
			["fontsize"] = 14,
			["font"] = "預設",
			["fontflags"] = "None",
			["x"] = 0,
			["justifyV"] = "TOP",
			["justifyH"] = "LEFT",
		},
		["statusicon"] = {
			["y"] = -40,
			["x"] = 320,
			["framelevel"] = 4,
			["h"] = 24,
			["w"] = 24,
			["hide"] = true,
		},
	},
	["arena5target"] = {
		["frame"] = {
			["y"] = -515,
			["h"] = 24,
			["x"] = 1243,
			["w"] = 78,
			["hide"] = true,
		},
	},
	["partypet4"] = {
		["frame"] = {
			["y"] = -484,
			["x"] = 212,
		},
	},
	["arena4target"] = {
		["frame"] = {
			["y"] = -468,
			["h"] = 24,
			["x"] = 1243,
			["w"] = 78,
			["hide"] = true,
		},
	},
	["global"] = {
		["bglist"] = "statusbar",
		["bordermousecolor"] = {
			["a"] = 0,
			["r"] = 1,
			["g"] = 1,
			["b"] = 0,
		},
		["bgcolor"] = {
			["a"] = 0.4,
			["r"] = 0,
			["g"] = 0,
			["b"] = 0,
		},
		["mpfadecolor"] = {
			["a"] = 0.5,
			["r"] = 1,
			["g"] = 1,
			["b"] = 1,
		},
		["shortk"] = 100000,
		["border"] = "Blizzard Tooltip",
		["powercolor"] = {
			{
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			}, -- [1]
			{
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.25,
			}, -- [2]
			{
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			}, -- [3]
			{
				["r"] = 0.71,
				["g"] = 1,
				["b"] = 0.92,
			}, -- [4]
			{
				["r"] = 0.5,
				["g"] = 0.5,
				["b"] = 0.5,
			}, -- [5]
			{
				["r"] = 0,
				["g"] = 0.82,
				["b"] = 1,
			}, -- [6]
			{
				["r"] = 0.5,
				["g"] = 0.32,
				["b"] = 0.55,
			}, -- [7]
			{
				["r"] = 0.3,
				["g"] = 0.52,
				["b"] = 0.9,
			}, -- [8]
			{
				["r"] = 0.95,
				["g"] = 0.9,
				["b"] = 0.6,
			}, -- [9]
			[11] = {
				["r"] = 0,
				["g"] = 0.5,
				["b"] = 1,
			},
			[13] = {
				["r"] = 0.4,
				["g"] = 0,
				["b"] = 0.8,
			},
			[18] = {
				["r"] = 1,
				["g"] = 0.611764705882353,
				["b"] = 0,
			},
			[17] = {
				["r"] = 0.788,
				["g"] = 0.259,
				["b"] = 0.992,
			},
			[0] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 1,
			},
		},
		["hidepartyinraid"] = true,
		["gray"] = {
			["a"] = 0.8,
			["r"] = 0.4,
			["g"] = 0.4,
			["b"] = 0.4,
		},
		["hpfadecolor"] = {
			["a"] = 1,
			["r"] = 1,
			["g"] = 0.1,
			["b"] = 0.1,
		},
		["hpgreen"] = {
			["a"] = 1,
			["r"] = 0,
			["g"] = 0.5,
			["b"] = 0,
		},
		["auracolor"] = {
			[""] = {
				["r"] = 0.8,
				["g"] = 0,
				["b"] = 0,
			},
			["Disease"] = {
				["r"] = 0.6,
				["g"] = 0.4,
				["b"] = 0,
			},
			["Buff"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["MyBuff"] = {
				["r"] = 0.5,
				["g"] = 0.5,
				["b"] = 0.6,
			},
			["Poison"] = {
				["r"] = 0,
				["g"] = 0.6,
				["b"] = 0,
			},
			["Curse"] = {
				["r"] = 0.6,
				["g"] = 0,
				["b"] = 1,
			},
			["Magic"] = {
				["r"] = 0.2,
				["g"] = 0.6,
				["b"] = 1,
			},
			["none"] = {
				["r"] = 0.8,
				["g"] = 0,
				["b"] = 0,
			},
		},
		["classcolor"] = {
			["HUNTER"] = {
				["r"] = 0.67,
				["g"] = 0.83,
				["b"] = 0.45,
			},
			["WARRIOR"] = {
				["r"] = 0.78,
				["g"] = 0.61,
				["b"] = 0.43,
			},
			["SHAMAN"] = {
				["r"] = 0,
				["g"] = 0.44,
				["b"] = 0.87,
			},
			["MAGE"] = {
				["r"] = 0.25,
				["g"] = 0.78,
				["b"] = 0.92,
			},
			["PRIEST"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["PALADIN"] = {
				["r"] = 0.96,
				["g"] = 0.55,
				["b"] = 0.73,
			},
			["WARLOCK"] = {
				["r"] = 0.53,
				["g"] = 0.53,
				["b"] = 0.93,
			},
			["DEMONHUNTER"] = {
				["r"] = 0.64,
				["g"] = 0.19,
				["b"] = 0.79,
			},
			["DEATHKNIGHT"] = {
				["r"] = 0.77,
				["g"] = 0.12,
				["b"] = 0.23,
			},
			["DRUID"] = {
				["r"] = 1,
				["g"] = 0.49,
				["b"] = 0.04,
			},
			["MONK"] = {
				["r"] = 0,
				["g"] = 1,
				["b"] = 0.59,
			},
			["ROGUE"] = {
				["r"] = 1,
				["g"] = 0.96,
				["b"] = 0.41,
			},
		},
		["font"] = "預設",
		["bg"] = "Flat Smooth",
		["hpred"] = {
			["a"] = 1,
			["r"] = 0.5,
			["g"] = 0,
			["b"] = 0,
		},
		["bartexture"] = "Flat Smooth",
		["classification"] = {
			["elite"] = "精英",
			["normal"] = "",
			["worldboss"] = "首領",
			["unknown"] = "??",
			["rareelite"] = "稀有精英",
			["rare"] = "稀有",
		},
		["bgmousecolor"] = {
			["a"] = 0.6,
			["r"] = 1,
			["g"] = 1,
			["b"] = 0,
		},
		["completecolor"] = {
			["r"] = 1,
			["g"] = 1,
			["b"] = 0,
		},
		["failcolor"] = {
			["r"] = 1,
			["g"] = 0,
			["b"] = 0,
		},
		["shadowcolor"] = {
			["a"] = 0.9,
			["r"] = 0,
			["g"] = 0,
			["b"] = 0,
		},
		["alpha"] = 1,
		["disableboss"] = true,
		["init"] = 9,
		["nK"] = "千",
		["borderaggrocolor"] = {
			["a"] = 0,
			["r"] = 1,
			["g"] = 0,
			["b"] = 0,
		},
		["channelcolor"] = {
			["r"] = 0,
			["g"] = 1,
			["b"] = 0,
		},
		["reactioncolor"] = {
			{
				["r"] = 0.8,
				["g"] = 0.3,
				["b"] = 0.22,
			}, -- [1]
			{
				["r"] = 0.8,
				["g"] = 0.3,
				["b"] = 0.22,
			}, -- [2]
			{
				["r"] = 0.75,
				["g"] = 0.27,
				["b"] = 0,
			}, -- [3]
			{
				["r"] = 0.9,
				["g"] = 0.7,
				["b"] = 0,
			}, -- [4]
			{
				["r"] = 0,
				["g"] = 0.6,
				["b"] = 0.1,
			}, -- [5]
			{
				["r"] = 0,
				["g"] = 0.6,
				["b"] = 0.1,
			}, -- [6]
			{
				["r"] = 0,
				["g"] = 0.6,
				["b"] = 0.1,
			}, -- [7]
			{
				["r"] = 0,
				["g"] = 0.6,
				["b"] = 0.1,
			}, -- [8]
			{
				["r"] = 0.8,
				["g"] = 1,
				["b"] = 0.8,
			}, -- [9]
			{
				["r"] = 1,
				["g"] = 0.8,
				["b"] = 0.8,
			}, -- [10]
		},
		["castcolor"] = {
			["r"] = 1,
			["g"] = 0.7,
			["b"] = 0,
		},
		["nM"] = "百萬",
		["initlegion"] = 1,
	},
	["boss3"] = {
		["frame"] = {
			["y"] = -450,
			["x"] = 1167,
			["w"] = 78,
			["h"] = 24,
		},
	},
	["arena2target"] = {
		["frame"] = {
			["y"] = -374,
			["h"] = 24,
			["x"] = 1243,
			["w"] = 78,
			["hide"] = true,
		},
	},
	["party1"] = {
		["buffgroup"] = {
			["y"] = -57,
			["x"] = 0,
			["count"] = 10,
			["h"] = 20,
			["rows"] = 2,
			["w"] = 20,
			["cols"] = 10,
		},
		["portrait"] = {
			["zoom2d"] = true,
			["bgcolor"] = {
				["a"] = 0.4,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["bordercolor"] = {
				["a"] = 0.777,
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["w"] = 50,
			["y"] = 0,
			["x"] = -1,
			["border"] = "Blizzard Tooltip",
			["bg"] = "Flat Smooth",
			["h"] = 50,
		},
		["combattext"] = {
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 52,
			["framelevel"] = 2,
			["y"] = -20,
			["x"] = 0,
			["fontsize"] = 12,
			["justifyV"] = "TOP",
			["h"] = 14,
			["justifyH"] = "CENTER",
			["hide"] = true,
		},
		["text3"] = {
			["pattern"] = "[curhp]/[maxhp]   [perchp]%",
			["shadowx"] = 0,
			["shadowy"] = 0,
			["w"] = 169,
			["framelevel"] = 2,
			["y"] = -21,
			["x"] = 50,
			["fontsize"] = 12,
			["h"] = 12,
			["justifyH"] = "RIGHT",
			["justifyV"] = "BOTTOM",
		},
		["infoicon"] = {
			["y"] = 0,
			["x"] = 50,
			["h"] = 16,
			["w"] = 16,
			["framelevel"] = 2,
		},
		["debuffgroup"] = {
			["w"] = 36,
			["x"] = 226,
			["rows"] = 3,
			["growth"] = "LRTB",
			["cols"] = 5,
			["y"] = -15,
			["h"] = 36,
			["count"] = 5,
			["spacing"] = 2,
			["showpie"] = true,
			["vspacing"] = 1,
			["counttfontflags"] = "OUTLINE",
			["push"] = "None",
		},
		["text6"] = {
			["pattern"] = "[gray_if_oor:距離過遠][gray_if_dead:死亡][gray_if_ghost:靈魂][gray_if_offline:離線]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 160,
			["framelevel"] = 4,
			["y"] = -25,
			["x"] = 55,
			["fontsize"] = 20,
			["h"] = 20,
			["justifyH"] = "LEFT",
			["justifyV"] = "CENTER",
			["font"] = "傷害數字",
		},
		["text1"] = {
			["pattern"] = "[name]",
			["shadowx"] = -1,
			["shadowy"] = -2,
			["w"] = 150,
			["framelevel"] = 2,
			["y"] = 0,
			["x"] = 70,
			["fontsize"] = 16,
			["h"] = 16,
			["fontflags"] = "None",
			["justifyH"] = "LEFT",
			["justifyV"] = "TOP",
			["font"] = "傷害數字",
		},
		["voiceicon"] = {
			["y"] = 7,
			["x"] = -8,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["text2"] = {
			["pattern"] = "[level] [class:race]",
			["shadowx"] = -1,
			["shadowy"] = -1,
			["w"] = 100,
			["framelevel"] = 2,
			["y"] = 11,
			["x"] = 52,
			["fontsize"] = 12,
			["h"] = 12,
			["justifyH"] = "LEFT",
			["justifyV"] = "TOP",
		},
		["lfgicon"] = {
			["y"] = -42,
			["x"] = 39,
			["circular"] = true,
			["h"] = 20,
			["w"] = 20,
			["alpha"] = 1,
			["framelevel"] = 4,
		},
		["castbar"] = {
			["spellfontsize"] = 14,
			["spellshadowy"] = -1,
			["timeshadowy"] = -1,
			["spelljustifyH"] = "CENTER",
			["iconw"] = 20,
			["h"] = 52,
			["timefontsize"] = 12,
			["timeh"] = 12,
			["spellfontcolor"] = {
				["a"] = 0.7,
				["b"] = 0.2,
				["g"] = 0.5,
				["r"] = 1,
			},
			["w"] = 220,
			["spelljustifyV"] = "CENTER",
			["y"] = 1,
			["x"] = 0,
			["iconx"] = 85,
			["timejustifyV"] = "CENTER",
			["spellw"] = 193,
			["baralpha"] = 0,
			["spellh"] = 14,
			["framelevel"] = 9,
			["hide"] = true,
			["spellx"] = 5,
			["timey"] = -36,
			["timeshadowx"] = -1,
			["iconalpha"] = 0,
			["alpha"] = 1,
			["icony"] = -27,
			["timefontcolor"] = {
				["a"] = 0,
				["b"] = 0.2,
				["g"] = 0.5,
				["r"] = 1,
			},
			["timew"] = 193,
			["iconh"] = 20,
			["spellshadowx"] = -1,
			["timejustifyH"] = "CENTER",
			["bgcolor"] = {
				["a"] = 0.2,
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["timex"] = 0,
			["spelly"] = -38,
		},
		["text5"] = {
			["pattern"] = "",
			["w"] = 100,
			["framelevel"] = 2,
			["y"] = -35,
			["x"] = 95,
			["fontsize"] = 10,
			["justifyV"] = "BOTTOM",
			["h"] = 10,
			["justifyH"] = "RIGHT",
			["hide"] = true,
		},
		["leadericon"] = {
			["y"] = 13,
			["x"] = 14,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["pvpicon"] = {
			["y"] = -12,
			["x"] = -12,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["text4"] = {
			["pattern"] = "[curmp]/[maxmp]   [percmp]%",
			["w"] = 169,
			["framelevel"] = 2,
			["y"] = -37,
			["x"] = 50,
			["fontsize"] = 12,
			["h"] = 12,
			["justifyH"] = "RIGHT",
			["justifyV"] = "BOTTOM",
		},
		["dispellicon"] = {
			["y"] = 0,
			["x"] = 52,
			["h"] = 50,
			["w"] = 50,
			["framelevel"] = 4,
		},
		["mpbar"] = {
			["baralpha"] = 1,
			["bgalpha"] = 0.3,
			["w"] = 170,
			["fade"] = true,
			["y"] = -38,
			["x"] = 51,
			["barcolormethod"] = "power",
			["framelevel"] = 1,
			["bgcolormethod"] = "power",
			["h"] = 13,
		},
		["looticon"] = {
			["y"] = -40,
			["x"] = -12,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["hpbar"] = {
			["baralpha"] = 1,
			["bgalpha"] = 1,
			["w"] = 170,
			["fade"] = true,
			["y"] = -18,
			["x"] = 51,
			["barcolormethod"] = "class",
			["h"] = 20,
			["framelevel"] = 1,
			["inc"] = true,
			["bgcolormethod"] = "classdark",
		},
		["raidtargeticon"] = {
			["y"] = 12,
			["x"] = 193,
			["h"] = 20,
			["w"] = 20,
			["framelevel"] = 4,
		},
		["frame"] = {
			["y"] = -292,
			["x"] = 41,
			["bordercolormethod"] = "classdark",
			["scale"] = 0.8,
			["w"] = 220,
			["h"] = 50,
		},
		["vehicleicon"] = {
			["y"] = -43,
			["x"] = -10,
			["framelevel"] = 4,
			["h"] = 20,
			["w"] = 20,
			["hide"] = true,
		},
		["statusicon"] = {
			["y"] = -40,
			["x"] = -12,
			["h"] = 24,
			["w"] = 24,
			["framelevel"] = 4,
		},
	},
	["arena3"] = {
		["frame"] = {
			["y"] = -421,
			["h"] = 24,
			["x"] = 1164,
			["w"] = 78,
			["hide"] = true,
		},
	},
	["arena4"] = {
		["frame"] = {
			["y"] = -468,
			["h"] = 24,
			["x"] = 1164,
			["w"] = 78,
			["hide"] = true,
		},
	},
}
